# Generated by Django 5.2.1 on 2025-05-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionCombinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('producto_principal', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RangoPromocionCombinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonificacion_producto', models.CharField(max_length=100)),
                ('bonificacion_cantidad', models.IntegerField()),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='promociones.promocioncombinada')),
            ],
        ),
    ]
